name: Updater

on:
  schedule:
  - cron: "0 */6 * * *"

  workflow_dispatch:

jobs:
  updater:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Run updater
        run: ./scripts/updater.sh
        env:
          WEBHOOK_JETBRAINS: ${{ secrets.WEBHOOK_JETBRAINS }}
